# Spring settings block
spring:
  datasource:
    url: jdbc:hsqldb:mem:pushkin
    driver-class-name: org.hsqldb.jdbcDriver
    username: SA
    password: SA
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
#      ddl-auto: update

